In [3]:
import requests
import pandas as pd
re_all = requests.get('https://lab.isaaclin.cn/nCoV/api/area?latest=1')

In [4]:
re_all_dict = re_all.json()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [1]:
re_all_dict

NameError: name 're_all_dict' is not defined

In [15]:
df_china.sum()

provinceShortName    青海海南湖南四川湖北香港陕西河南云南内蒙古广西上海辽宁新疆山西台湾吉林北京西藏重庆福建天津宁...
confirmedCount                                                    7830
suspectedCount                                                       0
curedCount                                                         133
deadCount                                                          170
dtype: object

In [17]:
df_china.sum()['confirmedCount']

7830

In [19]:
df_china.sum()['suspectedCount']

0

In [34]:
str1='abc\nefg'

In [35]:
print(str1)

abc
efg

In [28]:
 print('apple\torange')

apple	orange

In [36]:
df_all

,country,provinceName,provinceShortName,confirmedCount,suspectedCount,curedCount,deadCount,cities,comment,updateTime,createTime,modifyTime
0,印度,印度,印度,1,0,0,0,None,,1580375584426,1.580376e+12,1.580376e+12
1,法国,法国,法国,5,0,0,0,None,,1580337970975,1.580028e+12,1.580338e+12
2,斯里兰卡,斯里兰卡,斯里兰卡,1,0,0,0,None,,1580197409923,1.580182e+12,1.580182e+12
3,泰国,泰国,泰国,14,0,5,0,None,,1580197409923,1.580028e+12,1.580191e+12
4,尼泊尔,尼泊尔,尼泊尔,1,0,0,0,None,,1580139042967,1.580028e+12,1.580028e+12
5,中国,青海省,青海,8,0,0,0,"[{'cityName': '西宁', 'confirmedCount': 6, 'susp...",,1580383506136,NaN,NaN
6,中国,海南省,海南,46,0,1,1,"[{'cityName': '三亚', 'confirmedCount': 14, 'sus...",,1580361914824,NaN,NaN
7,中国,湖南省,湖南,277,0,2,0,"[{'cityName': '长沙', 'confirmedCount': 57, 'sus...",,1580361008012,NaN,NaN
8,中国,四川省,四川,142,0,1,1,"[{'cityName': '成都', 'confirmedCount': 59, 'sus...",,1580344920664,NaN,NaN
9,中国,湖北省,湖北,4586,0,90,162,"[{'cityName': '武汉', 'confirmedCount': 2261, 's...",待明确地区：治愈30,1580341233691,NaN,NaN
10,中国,香港,香港,10,0,0,0,[],,1580296326231,NaN,NaN
11,中国,陕西省,陕西,63,0,0,0,"[{'cityName': '西安', 'confirmedCount': 22, 'sus...",,1580357986027,NaN,NaN
12,澳大利亚,澳大利亚,澳大利亚,7,0,0,0,None,,1580292093247,1.580028e+12,1.580292e+12
13,日本,日本,日本,11,0,1,0,None,,1580347157693,1.580028e+12,1.580347e+12
14,中国,河南省,河南,278,0,2,2,"[{'cityName': '南阳', 'confirmedCount': 51, 'sus...",待明确地区：治愈2,1580358771411,NaN,NaN
15,加拿大,加拿大,加拿大,3,0,0,0,None,,1580275155211,1.580028e+12,1.580275e+12
16,马来西亚,马来西亚,马来西亚,7,0,0,0,None,,1580272196170,1.580028e+12,1.580272e+12
17,美国,美国,美国,5,0,0,0,None,,1580139042967,1.580028e+12,1.580083e+12
18,中国,云南省,云南,70,0,0,0,"[{'cityName': '昆明', 'confirmedCount': 21, 'sus...",,1580349699002,NaN,NaN
19,中国,内蒙古自治区,内蒙古,18,0,0,0,"[{'cityName': '包头', 'confirmedCount': 3, 'susp...",,1580358046457,NaN,NaN
20,中国,广西壮族自治区,广西,78,0,2,0,"[{'cityName': '桂林', 'confirmedCount': 18, 'sus...",,1580344255652,NaN,NaN
21,韩国,韩国,韩国,4,0,0,0,None,,1580139042967,1.580028e+12,1.580094e+12
22,新加坡,新加坡,新加坡,10,0,0,0,None,,1580298925726,1.580028e+12,1.580299e+12
23,中国,上海市,上海,112,0,5,1,"[{'cityName': '外地来沪人员', 'confirmedCount': 51, ...",治愈数据统一归属上海市公卫临床中心，暂无具体分区,1580369232882,NaN,NaN
24,中国,辽宁省,辽宁,41,0,1,0,"[{'cityName': '沈阳', 'confirmedCount': 9, 'susp...",,1580359617941,NaN,NaN
25,柬埔寨,柬埔寨,柬埔寨,1,0,0,0,None,,1580139042967,1.580130e+12,1.580130e+12
26,中国,新疆维吾尔自治区,新疆,14,0,0,0,"[{'cityName': '乌鲁木齐', 'confirmedCount': 7, 'su...",,1580346310886,NaN,NaN
27,中国,山西省,山西,35,0,1,0,"[{'cityName': '晋中', 'confirmedCount': 9, 'susp...",,1580338817415,NaN,NaN
28,中国,台湾,台湾,9,0,0,0,[],,1580378428363,NaN,NaN
29,中国,吉林省,吉林,14,0,1,0,"[{'cityName': '长春', 'confirmedCount': 4, 'susp...",,1580349214776,NaN,NaN
30,中国,北京市,北京,114,0,4,1,"[{'cityName': '海淀', 'confirmedCount': 24, 'sus...",待明确地区：确诊3死亡1,1580358469186,NaN,NaN
31,中国,西藏自治区,西藏,1,0,0,0,[],,1580341898534,NaN,NaN
32,中国,重庆市,重庆,182,0,1,0,"[{'cityName': '万州区', 'confirmedCount': 24, 'su...",,1580372679855,NaN,NaN
33,中国,福建省,福建,101,0,0,0,"[{'cityName': '福州', 'confirmedCount': 30, 'sus...",,1580349699002,NaN,NaN
34,芬兰,芬兰,芬兰,1,0,0,0,None,,1580337970975,1.580338e+12,1.580338e+12
35,中国,天津市,天津,30,0,0,0,"[{'cityName': '河北区', 'confirmedCount': 9, 'sus...",,1580379757775,NaN,NaN
36,中国,宁夏回族自治区,宁夏,17,0,0,0,"[{'cityName': '银川', 'confirmedCount': 9, 'susp...",,1580359073792,NaN,NaN
37,中国,河北省,河北,65,0,0,1,"[{'cityName': '沧州', 'confirmedCount': 12, 'sus...",,1580343892896,NaN,NaN
38,中国,广东省,广东,354,0,8,0,"[{'cityName': '深圳', 'confirmedCount': 98, 'sus...",待明确地区治愈2例,1580373406009,NaN,NaN
39,中国,贵州省,贵州,12,0,1,0,"[{'cityName': '黔南州', 'confirmedCount': 4, 'sus...",,1580345827434,NaN,NaN
40,中国,山东省,山东,158,0,1,0,"[{'cityName': '青岛', 'confirmedCount': 21, 'sus...",,1580369474773,NaN,NaN
41,中国,江西省,江西,162,0,5,0,"[{'cityName': '南昌', 'confirmedCount': 46, 'sus...",,1580358348442,NaN,NaN
42,中国,甘肃省,甘肃,26,0,0,0,"[{'cityName': '兰州', 'confirmedCount': 14, 'sus...",,1580346976122,NaN,NaN
43,越南,越南,越南,2,0,0,0,None,,1580139042967,1.580028e+12,1.580028e+12
44,中国,澳门,澳门,7,0,0,0,[],,1580176234189,NaN,NaN
45,中国,浙江省,浙江,428,0,4,0,"[{'cityName': '温州', 'confirmedCount': 172, 'su...",,1580346673523,NaN,NaN
46,中国,安徽省,安徽,200,0,2,0,"[{'cityName': '合肥', 'confirmedCount': 39, 'sus...",,1580345706671,NaN,NaN
47,中国,江苏省,江苏,129,0,1,0,"[{'cityName': '苏州', 'confirmedCount': 24, 'sus...",,1580345404749,NaN,NaN
48,阿联酋,阿联酋,阿联酋,1,0,0,0,None,,1580276787684,1.580277e+12,1.580277e+12
49,中国,黑龙江省,黑龙江,43,0,0,1,"[{'cityName': '哈尔滨', 'confirmedCount': 13, 'su...",,1580347278609,NaN,NaN
50,德国,德国,德国,4,0,0,0,None,,1580252372598,1.580167e+12,1.580252e+12

In [5]:
re_all = requests.get('https://lab.isaaclin.cn/nCoV/api/area?latest=1')
re_all_dict = re_all.json()     
df_all = pd.DataFrame(data=re_all_dict['results'])  # change virus data to dataframe
df_china = df_all[df_all['country']=='中国'][['provinceShortName','confirmedCount', 'suspectedCount', 'curedCount', 'deadCount']]  #virus data of China only (33 parts)

In [6]:
df_china

   provinceShortName  confirmedCount  suspectedCount  curedCount  deadCount
5                 西藏               0               1           0          0
20                青海               0               1           0          0
21                澳门               2               0           0          0
22                安徽               9               0           0          0
23                江苏               5               0           0          0
24               黑龙江               2               0           0          0
25                浙江              27               0           0          0
26                陕西               3               0           0          0
27                辽宁               3               0           0          0
28                香港               2               0           0          0
29                台湾               1               0           0          0
30               内蒙古               0               1           0          0
31                湖南               9               0           0          0
32                四川               8               0           0          0
33                湖北             444               0           0          0
34                海南               5               0           0          0
35                河南               5               0           0          0
36                云南               2               0           0          0
37                上海              16               0           0          0
38                广西               5               0           0          0
39                江西               7               0           0          0
40                北京              22               0           0          0
41                山西               1               0           0          0
42                吉林               1               0           0          0
43                新疆               2               0           0          0
44                福建               5               0           0          0
45                重庆               9               0           0          0
46                天津               4               0           0          0
47                贵州               3               0           0          0
48                广东              32               0           0          0
49                河北               1               0           0          1
50                甘肃               2               0           0          0
51                宁夏               1               0           0          0
52                山东               6               0           0          0